services:
  zookeeper:
    image: bitnami/zookeeper:${ZOOKEEPER_VERSION}
    container_name: zookeeper
    ports:
      - 2181:2181
    environment:
      ZOO_ENABLE_AUTH: "yes"
      ZOO_SERVER_USERS: ${KAFKA_DEFAULT_USERS:-}
      ZOO_SERVER_PASSWORDS: ${KAFKA_DEFAULT_PASSWORDS:-}
      ZOO_CLIENT_USER: ${KAFKA_DEFAULT_USERS:-}
      ZOO_CLIENT_PASSWORD: ${KAFKA_DEFAULT_PASSWORDS:-}
    networks:
      - yan
    restart: unless-stopped

  kafka:
    image: bitnami/kafka:${KAFKA_VERSION}
    container_name: kafka
    ports:
      - 9092:9092
      - 9093:9093
    environment:
      BITNAMI_DEBUG: "yes"
      ALLOW_PLAINTEXT_LISTENER: "no"
      KAFKA_BROKER_ID: 1
      KAFKA_ENABLE_KRAFT: "no"
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_LISTENERS: INTERNAL://:9092,CLIENT://:9093
      KAFKA_CFG_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,CLIENT://localhost:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: CLIENT
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:SASL_PLAINTEXT,CLIENT:SASL_PLAINTEXT
      KAFKA_CFG_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
      KAFKA_CLIENT_USERS: ${KAFKA_DEFAULT_USERS:-}
      KAFKA_CLIENT_PASSWORDS: ${KAFKA_DEFAULT_PASSWORDS:-}
      KAFKA_INTER_BROKER_USER: ${KAFKA_DEFAULT_USERS:-}
      KAFKA_INTER_BROKER_PASSWORD: ${KAFKA_DEFAULT_PASSWORDS:-}
      KAFKA_ZOOKEEPER_PROTOCOL: SASL
      KAFKA_ZOOKEEPER_USER: ${KAFKA_DEFAULT_USERS:-}
      KAFKA_ZOOKEEPER_PASSWORD: ${KAFKA_DEFAULT_PASSWORDS:-}
    networks:
      - yan
    depends_on:
      - zookeeper
    restart: unless-stopped

  kafka-ui:
    image: provectuslabs/kafka-ui:${KAFKA_UI_VERSION}
    container_name: kafkaui
    ports:
      - 8080:8080
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL: SASL_PLAINTEXT
      KAFKA_CLUSTERS_0_PROPERTIES_SASL_MECHANISM: PLAIN
      KAFKA_CLUSTERS_0_PROPERTIES_CLIENT_DNS_LOOKUP: use_all_dns_ips
      KAFKA_CLUSTERS_0_PROPERTIES_SASL_JAAS_CONFIG: "org.apache.kafka.common.security.plain.PlainLoginModule required username='${KAFKA_DEFAULT_USERS:-}' password='${KAFKA_DEFAULT_PASSWORDS:-}';"
      KAFKA_CLUSTERS_0_DISABLELOGDIRSCOLLECTION: "true"
    networks:
      - yan
    depends_on:
      - zookeeper
      - kafka
    restart: unless-stopped

networks:
  yan:
    driver: bridge
